! Observed South Pacific pentatonic balafon tuning Helmholtz_Ellis p. 518 nr.93.scl
! Created using Scale Workshop 2.0.1
!
! https://sevish.com/scaleworkshop/?n=Observed%20South%20Pacific%20pentatonic%20balafon%20tuning%2C%20Helmholtz%2FEllis%20p.%20518%2C%20nr.93&l=5m._aa._j1._p3._2F1&k=p&y=46&version=2.0.1
!
Observed South Pacific pentatonic balafon tuning, Helmholtz/Ellis p. 518, nr.93
 5
!
 202.000000
 370.000000
 685.000000
 903.000000
 2/1
